version: '2'
services:
  express-api:
    build: ./
    image: gcr.io/rec-survey/rec-survey-api
    container_name: req-survey-api
    tty: true
    ports:
      - "2000:2000"
    volumes:
        - mediafile:/mediafile:ro
  nginx:
    build: ./src/views
    image: gcr.io/rec-survey/rec-survey-view
    container_name: req-survey-view
    tty: true
    ports:
      - "443:443"
      - "80:80"
  database:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  mediaserver:
    image: kurento/kurento-media-server:xenial-latest
    container_name: kurento
    ports:
      - "8888:8888"
    volumes:
      - mediafile:/mediafile
volumes:
  mediafile:
