apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mediaserver
  name: mediaserver
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mediaserver
    spec:
      containers:
      - image: kurento/kurento-media-server:xenial-latest
        name: kurento
        ports:
        - containerPort: 8888
        resources: {}
        volumeMounts:
        - mountPath: /mediafile
          name: mediafile
      restartPolicy: Always
      volumes:
      - name: mediafile
        persistentVolumeClaim:
          claimName: mediafile
status: {}
